---
branches:
  - main
  - name: develop
    prerelease: true

plugins:
  - "@semantic-release/github"
  - "@semantic-release/commit-analyzer":
      preset: conventionalcommits
  - "@semantic-release/release-notes-generator"
  - - semantic-release-replace-plugin
    - replacements:
        - files:
            - src/**/devcontainer-template.json
          from: '"version": ".*"'
          to: '"version": "${nextRelease.version}"'
          countMatches: true
          results:
            - file: src/git-devcontainer/devcontainer-template.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/git"
    - assets:
        - src/**/devcontainer-template.json
        - "*/**/README.md"
      message: "chore: ${nextRelease.version} [skip ci]"
